- lib/config/command.js
- lib/config/exec.js
- lib/config/load.js
- lib/monitor/run.js
- lib/nodemon.js
- test/cli/exec.test.js
- test/cli/parse.test.js
- test/config/load.test.js
- test/config/parse-exec.test.js
- test/events/complete.test.js
- test/fork/config.test.js
- test/lib/require.test.js
- test/monitor/changed-since.test.js
- test/monitor/match.test.js
It was losing quotes around arguments, and in fact only needs to capture the first element in the string as the exec, and the rest could be left as is (if I keep the `sh` method of execution).
Fixes #448
> Fixed exec parser

- lib/monitor/watch.js
- test/fork/watch-restart.test.js
This changes the behaviour of the option --delay n
This means that as soon as one file changes, nodemon will restart the
script. The previous behavior was to wait for n seconds before
restarting the process. With throttle, the function gets called when the
first file changes. After that, all file changes in the interval [t,t+n]
are ignored
> changed --delay option: it now works like a throttle instead of with setTimeout

- lib/monitor/run.js
Detect if `ps` is available, and if not, just try to kill the parent
> Fixed #454

- lib/config/exec.js
- lib/monitor/run.js
- package.json
- test/fixtures/packages/start-ignored/package.json
- test/lib/require.test.js
Currently if you require nodemon, and pass it an object with `script` it'll try to load `package.start` *first*. This is wrong.
Tests based on this [comment](https://github.com/JacksonGariety/gulp-nodemon/issues/49#issuecomment-70619759).
Ref https://github.com/JacksonGariety/gulp-nodemon/issues/49
> Required nodemon should prioritise options over discovered script

- lib/monitor/run.js
use nodemon as a require module:
```shell
$ npm install nodemon --save
```
```javascript
var nodemon = require('nodemon');
nodemon({
script: 'app.js',
args: ['--port 10086', '--delay 2000'],
nodeArgs: ['--harmony'],
watch: '/path/to/watch',
ext: 'json,js'
}).on('restart', function (files) {
});
```
when nodemon emit **restart** event, an error occurred because of the args is missing.
It also get the error when you run nodemon in the shell when it restarts:
```shell
$ nodemon --harmony -e "js, json" -w '/path/to/watch' app.js "--prot 10086" "--delay 2000"
```
in [`lib/monitor/run.js#L51-L58`](https://github.com/remy/nodemon/blob/master/lib/monitor/run.js#L51-L58) cause this error:
```javascript
cmd.args = cmd.args.map(function (arg) {
if (arg.indexOf(' ') !== -1) {
arg = '"' + …
```
> parse cmd.args

- lib/monitor/offset.js
Use try/catch when trying to work out the offset, because if we don't have permission, we shouldn't vomit.
> Fixed #476

- .travis.yml
- lib/monitor/run.js
- lib/utils/index.js
`rs` now works again on windows when app has crashed.
> Fixed #499

- lib/config/exec.js
- lib/config/index.js
- lib/monitor/run.js
- lib/utils/index.js
- test/cli/exec.test.js
- test/cli/parse.test.js
- test/config/load.test.js
- test/events/scripts.test.js
- test/utils/stringify.test.js
Related issue: #530. See both commit messages for more details. The second commit is related to the fact that nodemon prints out a line like this:
```
22 Apr 13:34:07 - [nodemon] starting `coffee --nodejs --debug --harmony app.coffee`
```
This is wrong because the two node flags should be grouped as a single argument, so it would look more correct as `--nodejs "--debug --harmony"`. I thought making the output clear was important, so I fixed how command stringification worked. In the process, there is a test that was strangely broken because it seems to group arguments when it probably should not be. Let me know what you think we should do about that.
> Fix running coffee scripts with application --args

- lib/spawn.js
- test/monitor/ignore.test.js
This change allows nodemon to properly work with all versions of io.js.
This fixes #509
> spawn: Change node version checking logic

- lib/monitor/run.js
- test/events/complete.test.js
- test/fixtures/events/nodemon.json
Previously, a `'quit'` listener in `nodemon.json` would not execute.
This is useful to have for cleanup in various cases. I was putting together a `nodemon.json` that was compatible with [naught](https://github.com/andrewrk/naught) in my case but I am sure there are plenty of others.
This patch simply iterates through all other `'quit'` listeners before calling `process.exit(0)`, to make sure they execute.
I have additionally removed some duplicated code in the SIGINT handler and added a test.
> Fix nodemon.json's 'quit' listener and add test.

- lib/config/watchable.js
I've started using nodemon, and noticed it doesn't restart on changes.
After looking online and trying few stuff (none worked), I decided to dive in.
When using --dump, I noticed 'useWatch' was false.
I then tested fs.watch independently, and it worked.
After looking a bit more, I found nodemon is testing watch by waiting 1000 ms and assuming
a watch event should be triggered. I'm not sure why, but inside nodemon, the event seems to trigger only after 4 seconds (~);
When adding the fs.closeSync() line, the watch triggers, and everything works.
It shouldn't matter, but some extra information regarding my environment:
node: v0.12.2
nodemon: v1.3.7
OS: Windows 8.1 x64
> nodemon doesn't restart on changes - watch test failure

- package.json
[node-touch](https://github.com/isaacs/node-touch) has a bug where bin file is missing she-bang on version tagged v0.0.4 (automatically depended by nodemon) and impacting other modules depending on the bin file (such as libpq, bcrypt... on node-gyp rebuild cmd) thus breaking npm install.
Steps to reproduce
cd /tmp/
mkdir foo
cd foo
npm install touch@0.0.4
Install any lib that requires node-gyp rebuild
npm install libpq
> Bump node-touch to 1.0.0

- lib/config/checkWatchSupport.js
It seems to be correct in `unlimit` rather than `ulimit`.
> Fix a "unlimit" typo on comment

- lib/cli/parse.js
- lib/config/load.js
- lib/monitor/watch.js
- package.json
- test/cli/parse.test.js
- test/fork/watch-restart.test.js
- test/monitor/match.test.js
Pass the `usePolling` flag to Chokidar when in legacy mode, which is supposed to/hopefully fix containers watching network attached drives.
Fixes #639
Fixes #633
> fix: restore --legacy-watch

- faq.md
Apparently, spelling supersede as supercede is [regarded as an error](http://www.merriam-webster.com/dictionary/supercede).
> docs: fix faq typo

- lib/config/exec.js
Fix a bug that caused `.json` file to not be watched outside of a coffeescript environment,
and improves the extension formatting regex.
Closes #643
> fix: JSON extension not watched outside of coffeescript

- lib/config/exec.js
Fix a bug that caused ".json" files to not be watched by default.
closes #643
> fix: JSON extension not watched when "scriptExt" is defined

- lib/config/exec.js
In node the file extension is optional, so by default nodemon should watch
js and json files.
Closes #710
> Watch js, json files by default

- lib/cli/parse.js
- lib/monitor/watch.js
Passes a polling interval to chokidar.watch() for legacy polling. Very useful for those of us running nodemon in a docker-machine image / VirtualBox VM.
> feat: support --polling-interval command line arg

- lib/nodemon.js
Use case: in my ``package.json`` I have two "nodemon" entries, one for linting and the other one for my real server. I run them all in parallel and when I type "rs" I want only one of them to catch it.
As I cannot configure them individually (shared nodemon.json), I added "--no-stdin" to one, but I found it weird that it did not do what was expected.
This patch will make "--no-stdin" actually do what it claims and stop listening for stdin, even if "restartable" is enabled.
> Don't watch for 'rs' when --no-stdin is provided

- doc/option-parsing-logic.md
Fixed a typo in `doc/option-parsing-logic.md`.
> Fixed a typo

- faq.md
Took me some time too figure it out. The option in nodemon.json is "legacyWatch" and not "legacy-watch". I guess that could be helpful for other users too.
> Fixed an error in the faq

- README.md
- doc/cli/config.txt
- doc/cli/help.txt
- lib/cli/parse.js
- lib/config/load.js
- test/cli/parse.test.js
Per original PR / conversation by @kentcdodds & @remy in #755, this implements
the `--config <file>` option allowing users to load an arbitrary config file
instead of being bound to the default `$PWD/nodemon.json`.
Patch includes:
* `--config` option parsing
* Documentation updates
* light (maybe sufficient?) unit test coverage
> load: Add ability to specify custom config file (reboot). fixes #755

- package.json
Old versions of touch install a binary that may conflicts with system, like [here](https://github.com/Homebrew/brew/issues/2891).
> chore: touch@3.1.0

- lib/utils/index.js
It happened with electron.js. Maybe some wrapper module has a native nature
> fix: catch module.parent.filename === undefined

- doc/requireable.md
I kept getting this annoying problem after following this tutorial which is best described in this gulp thread. https://github.com/JacksonGariety/gulp-nodemon/issues/77. I'm not using gulp but the problem is the same. By adding process.exit() on nodemon quit the problem goes away smoothly.
Maybe add this process.exit() hint in the docs here?
> process.exit() hint

- lib/monitor/run.js
- If the user configured a *nix compatible npm script where the path contained a forward slash, that failed under windows, since cmd.exe treated that as a command line argument.
- The quote handling was not 100% correct under windows, the whole path needs to be quoted, not just the segments it is also modified.
> Fix executable path handling under windows

- lib/monitor/run.js
I'm using nodemon in a docker container with a restart policy configured to restart the container in case it crashes. If my app crashes, nodemon exits with code 0 and thus docker assumes it was a graceful exit, so it does not restart my container. I don't see the harm in changing the exit code here to reflect an unexpected termination, given that this path is only exercised in the event of a crash.
> Exit with code 1 on crash if --exitcrash

- lib/config/exec.js
- test/cli/exec.test.js
Fixes #810 
Allows the ability to watch file extensions such as `ts.d` without it triggering when a `.ts` or `.d` file is changed.
> fix: Add support for multi-level file extensions

- lib/cli/parse.js
- lib/config/load.js
If I have a nodemon.json config file with an `exec` property, then this is automatically appended with ` index.js` when running `nodemon` standalone.
I would expect this to be equivalent to running `nodemon --exec "my cmd"` - that is providing an `exec` prevents defaulting of `script` to index.js.
To resolve, move the code which defaults the `script` property when `exec` is undefined to after the config files have been read, so that the behaviour is the same irrespective of whether properties are set in CLI flags or in nodemon.json.
> fix: read config file before defaulting script parameter

- faq.md
This change adds quotations for -c option
Otherwise the terminal cannot tell whether `--exitcrash` is an option for `nodemon` or `forever`, causing it to fail to start
> Fix for "Using nodemon with forever" section in FAQ

- README.md
- doc/cli/help.txt
- lib/config/exec.js
Updated code to add .mjs extension, per discussion in #1133.
Unfortunately was unable to run updated code or tests on my Node 8.7.0 installation due to multiple issues with 'npm install'.  Searched the issues list and there were many other people having trouble here too.  I tried the various workarounds suggested in those issues and none of them resolved the issue for me.  The one I couldn't get past was, "404 Not Found: ansi-styles@https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.0.tgz".
I didn't see test cases around the other default file extensions, so I didn't extend the tests to add extension tests.
> fix #1133 Support for .mjs es6 modules

- lib/config/exec.js
- lib/config/load.js
- lib/monitor/match.js
- lib/monitor/run.js
- lib/utils/index.js
- package-lock.json
- package.json
- test/config/load.test.js
Also updating some deps and linting tweaks.
Fixes #1045
> fix: pass through execArgs from config

- lib/monitor/watch.js
Fixes the issue where express is a js based project, but the executable
is `www`, so it misses on the match. So now nodemon will watch for
matching extensions but *also* the script the user gave.
Fixes #461
Note that this can't handle the situation where npm is used to run `node
./bin/www` as nodemon can't split out a package script command.
> feat: watch script regardless of extension

- lib/monitor/run.js
- package-lock.json
- package.json
Originally used ps-tree which relied on `ps` on *nix. But if the system
didn't have `ps` at all, we'd try to kill the child process, but alas
this would not always work, as we're spawning `sh` and _then_ node, so
the kill would only kill the `sh` process, and not the running node
process.
The new @remy/pstree lib sniffs for `ps` and defers to ps-tree,
otherwise it will walk /proc and map the PPID to the child process
allowing nodemon to fully clean up.
> fix: if no ps, walk /proc to kill child fully

- lib/config/exec.js
- lib/nodemon.js
- test/cli/exec.test.js
Add support for `--ext ''`; add tests for `--ext '.'` and `--ext '*'`.
Caveat: does not match extension-less files, see: https://github.com/remy/nodemon/issues/743#issuecomment-352405647.
> feat: support wildcard extension matching

- .github/CONTRIBUTING.md
- .npmrc
- .travis.yml
- faq.md
I also noticed that `jshint` gives a ton of errors when used with the `.jshintrc` in the repo - is still worth keeping around as it seems it is not used anyways?
> chore: add .npmrc which explicitly enables package-lock; some minor doc tweaks

- lib/monitor/match.js
Absolute paths being watched meant that they had a `**` added at the start of the `watch` array, which lead to minimatch failing to match the change. So only add the leading glob if it's a relative directory.
Fixes #1181
Fixes #749
> fix: defined directory watching

- lib/monitor/run.js
Fixes #1036 - the no-stdin wasn't passing the process.stdin to the
child.
> fix: pass stdin to child process on -I

- lib/config/defaults.js
- lib/monitor/watch.js
Changed to passing Chokidar simple strings instead of custom regexp, only had to prefix with `**/` to get it to match the ignore directories properly.
Fixes #916
> fix: properly ignore defaults, don't match partial

- lib/monitor/watch.js
The number of watched files was correct, but showed (incorrectly) a
cumulative total of watched files (i.e. 1 + 2 + 3 + 4 etc).
Fixes #1194
> fix: incorrect count of watch files being reported

- lib/monitor/run.js
> fix: don't use fork with `node inspect`

- lib/config/exec.js
- test/cli/exec.test.js
- Watch both `js` and `mjs` files if the script is either a `js` or `mjs` file or file with no extension. (For some reason that was before only the case when the main script was a CoffeeScript file xD)
- Some cleanup
> Watch both js and mjs files

- lib/monitor/run.js
This is a weird case where stdin isn't fully connected and throws in
ubuntu 16.04 (replicated in a Docker image).
Fixes #1195
> fix: swallow child.stdin err

- lib/config/defaults.js
- lib/config/index.js
- lib/monitor/match.js
- lib/monitor/run.js
- lib/monitor/watch.js
- lib/nodemon.js
Previous the rules weren't matching fully inside of chokidar, requiring
that, for instance, node_modules is written as **/node_modules/**.
I've also tidied up what's printed in verbose mode, so it doesn't print
default ignores, and doesn't print the full path of an ignored
directory.
This change _also_ fixes notifications from chokidar from user ignored
paths (using the `cwd` argument). This should fix #1202
>  fix: correctly pass ignored rules to chokidar

- lib/monitor/watch.js
Make any permission errors silent, since it the most likely case we don't need them at all.
Fixes: #1213
> fix: ignorePermissionErrors in chokidar

- lib/monitor/match.js
- lib/monitor/watch.js
> fix: don't ignore dot-directories

- lib/monitor/run.js
This fixes node@6.0.0, but it's a hack, so I'm going to emit a message
saying that non-LTS is not supported.
Fixes #1234
> fix: sniff for child.stdout before using it

- lib/monitor/run.js
This change takes code from npm's cli to change the way the arguments
passed to nodemon are interpreted.
Removes path.normalize and replaces with windowsVerbatimArguments
Fixes #1236
> fix: wrongly normalizing slashes in windows

- doc/cli/help.txt
- lib/help/index.js
- lib/utils/colour.js
- package-lock.json
- package.json
> fix: make clear where more opts are in help

- lib/config/load.js
- test/cli/exec.test.js
Fixes #1263
The way it works:
- If the script is detected via index.js from the directory, or from the
package, then all the arguments on the CLI are shifted to execArgs
- If there was a double-dash on the CLI args, then only those before the
double-dash are given to execArgs and the rest remain passed to the
script
> feat: feed args to exec when detecting script

- test/fixtures/some 'file
- test/fixtures/some \file
- test/fixtures/some file
- test/fixtures/some"file
- test/fixtures/some\"file
- test/fork/run-mac-only.test.js
- test/fork/run.test.js
> fix: make it possible for windows to checkout

- lib/monitor/run.js
Fixes #1251
Only converts the first exec arg from `/` to `\` rather than all using `path.normalize`
> fix: windows exec resolution

- lib/monitor/run.js
- package-lock.json
- package.json
Fixes #1268 
This means that instead of 
```bash
nodemon --exec node_modules/.bin/ts-node server.ts
```
You can do:
```bash
nodemon --exec ts-node server.ts
```
And equally supports this technique: https://twitter.com/housecor/status/962347301456015360
> feat: try to resolve exec in node_modules/.bin

- lib/monitor/watch.js
- package.json
Uses array passed to Chokidar of directories, instead of individually listing them causing overlap of files (and miscount).
Fixes #1283
> Fix: watch count regression

- lib/config/load.js
> fix: prevent throw when args missing

- lib/config/index.js
- lib/monitor/watch.js
- lib/utils/log.js
- package-lock.json
- package.json
- test/monitor/count.test.js
- test/monitor/run.test.js
Fixes #1294
Fixes #1305 (though couldn't confirm - just looks very similar)
I've gone back and forth on this Chokidar option `cwd` and in this fix
I've removed it from the config. I've checked the issues that were
raised that caused me to add the option, and they still appear to pass
in the tests, so I believe it's okay.
However, it _might_ come back in - just a note for Future @remy.
>  fix: node_modules watched off relative path

- lib/monitor/watch.js
Fixes #1317
Originally a new Set was generated upon every individual file (or dir)
watched. This typically doesn't take a long time, but if there's 10,000
files to watch, it's very, very slow. Moving this logic out to the ready
event instead, cuts all the processing time of the watch right down.
> fix: increase perf of watching large file count

- faq.md
- lib/monitor/run.js
- lib/nodemon.js
Fixes #1386
Also sends the correct signal codes on exit - so instead of $?=1 on
ctrl-c, you'll see $?=130 as per http://tldp.org/LDP/abs/html/exitcodes.html
> fix: send proper quit signal on ctrl-c

- lib/nodemon.js
Fixes #1389
Fixes #1390
Ref #1386
Means that ctrl^l does not instantly clear the terminal. It requires a
new line directly after.
> fix: revert stdin handling

- lib/monitor/run.js
This PR removes the special handling of exit code 2.
Not only `mocha` but also `stylelint` will sometimes exit with code 2, resulting in unexpected behaviour from nodemon. (It exits, and stops monitoring.)
The ` || true` workaround is unusual and easy to forget. I only ever remember to add it *after* I have been bitten!
If there is [no special reason](https://github.com/remy/nodemon/issues/627#issuecomment-139053515) to keep the special handling of code 2, then I think it would be best to remove it.
(In the case when a developer does provide a non-parseable command, which exits with code 2, an error is already reported to the console. So we won't be keeping developers in the dark by not quitting. After this PR, the developer will need to hit Ctrl-C to exit nodemon, in order to fix their …
> Remove the special handling of exit code 2

- doc/cli/help.txt
Small update so that `nodemon -h` mentions that `.json` files are now watched by default.
P.S. The change fixing #643 may have been considered as a breaking change, and reflected by bumping major version number. Updating some apps to above nodemon v1.7.0 require adaptation of the config...
P.P.S. Thanks for creating nodemon, super useful piece of software.
> docs: update help.txt

- lib/monitor/watch.js
- test/fixtures/configs/watch-options.json
- test/fork/run-mac-only.test.js
- test/monitor/watch.test.js
Fixes #1405 
Also fixed the condition for running `run-mac-only.test.js` since the test suite didn't pass on my Linux computer.
>  fix: properly pass options to chokidar

- package-lock.json
- package.json
Today i was preparing our projects for the LTS release of Node.js 10 but was stopped as your package is using a version of chokidar that was using a dependency (upath) which prevents any version beyond 9 (https://github.com/anodynos/upath/blob/v1.0.2/package.json#L43) so i've just bumped chokidar to the first version that has fixed this (https://github.com/paulmillr/chokidar/commit/11aea72ad7c65216a0f767142ce57151c7b3d0c1).
This issue will happen to anybody that is using a lockfile (specifically `yarn.lock`) that references any version of `nodemon` up to the current release and switch to node 10 (which could happen more and more often after the LTS release 😉).
> Fix nodemon installation for node 10.x and beyond

- faq.md
Added quotes around the `console.clear` section of the "How to clear the console on restart" section.
> Add quotes to faq.md

- .npmignore
- Dockerfile
- lib/monitor/run.js
- test/docker.sh
- test/fork/run-mac-only.test.js
Fixes #1463
Fixes #1469
Fixes #1464
> Fix new pstree consumption

- .travis.yml
- lib/monitor/run.js
- package-lock.json
- package.json
Fixes node 11's `rs` support. Somehow required that the `process.stdin` to be disconnected from the child before the stream is resumed (whereas previously it seemed that it would automatically happen…possibly a node 11 bug).
> fix: `rs` in node@11

- lib/utils/index.js
If a zero-length string is passed, it does not get properly quoted, and then it is not properly passed to the child process
I noticed this issue when using nodemon to monitor a wrapper script, where i basically pass a bunch of arguments like function arguments.
TODO: update the commit message to fit your convention. I just did this quickly in the github editor.
> Quote zero-length strings in arguments

- lib/config/defaults.js
`ts-node` is the standard for running typescript node programs on development mode.
Adding this line will enable everyone with a `tsconfig.json` to have a full-refresh server watching experience. (:
> feat: add TypeScript to default execPath

- LICENSE
- lib/monitor/run.js
Fixes #1633
Multiple parts but all localised to run.js:
- Refactor the kill logic to be simpler
- Consistently use pstree to determine sub process list
- Pipe stderr through nodemon to squash `sh -c` error warning
Bug was caused by waiting on multiple sub processes and if they all
ended the logic would only subtract one from the count list (rather
than the total number).
I've refactored the code so that it doesn't use the `kill -0 <pid>` as
this was a little confusing to read (it's effectively a no op) and
switched to using pstree to test if any sub processes are still running.
The logic for killing the processes has also been refactored to
simplify. Before it would fork the logic based on whether `ps` existed
on the system.
Now it uses the same logic with the exception of the kill signal …
> fix: ubuntu loop waiting for sub processes

- test/fixtures/sigint.js
- test/misc/sigint.test.js
- test/utils.js
The aim of this PR is to fix some issues in SIGINT test.
Due to combination of the following effects, the SIGINT test does not actually test what it is made for:
1. The callback of `string.replace` method takes the child pid from incorrect parameter:
https://github.com/remy/nodemon/blob/cd45d74593be411eba39481e5a8360c39079b118/test/misc/sigint.test.js#L16-L22
According to [MDN]( https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_function_as_a_parameter), the first parameter contains entire substring, not the first capture group. As the result, the `childPID` contains string, not just number (“pid: 1234”).
2. The test application ignores SIGINT signal and keeps hanging indefinitely: …
> test: make sigint test to actually check child pid

- doc/cli/help.txt
- doc/cli/options.txt
- lib/nodemon.js
When watching for single files with the `--watch`  or JSON `watch` functionality and with verbose logging enabled, nodemon logs "watching dir(s)" when not all rules may be directories. This initially threw me off to believe that nodemon did _not_ support watching single files, which upon further review, is clearly not the case (i.e. single file works as intended).
Example output:
```
[nodemon] 1.19.4
[nodemon] reading config ./nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): src/next.config.js src/server.ts
[nodemon] watching extensions: js,ts
[nodemon] starting `yarn run start:development:docker`
[nodemon] spawning
[nodemon] child pid: 44
[nodemon] watching 2 files
```
This pull request fixes these typos to "path(s)" in the verbose logging and "path" …
> docs: changed logging and docs to reflect support for single file watching

- bin/postinstall.js
Respect official environment variable to hide codecollective notifications OPENCOLLECTIVE_HIDE
> fix: respect env.OPENCOLLECTIVE_HIDE

- lib/config/load.js
- lib/monitor/run.js
- lib/monitor/watch.js
- test/config/load.test.js
- test/fixtures/packages/main-and-start/package.json
Fixes #1758
The combination of using a package.main (which sets the script position to index zero) and using the -- stop slurp meant that the arguments had the script appended to the end instead of prepended to the start. The net result meant that when the script was forked, it would drop the first user arg.
See diff for details of the fix - a simple check against null.
> fix: package.main with -- arguments

- lib/monitor/run.js
- lib/monitor/watch.js
- test/monitor/run.test.js
Updated
1. test/monitor/run.test.js: to run the test which was previously skipped.
2. lib/monitor/run.js: to handle the start on change only case (-C/--on-change-only) by adding an early exit.
3. lib/monitor/watch.js: to precheck config.options.execOptions before accessing script.
> fix: runOnChangeOnly=true

- lib/monitor/match.js
- test/monitor/match.test.js
Fixes: #1784
This fixes the watch/ignore rules where the config is ignoring
the relative local path of ./ - this fix was in place for the
positive (watch) test but not patched for the negative (ignore).
> fix: ignore ./<path> on cwd

- .travis.yml
No longer testing in node@8 as of nodemon@2.0.5
Adding node@14 and dropping non-LTS targets (odd versions).
> chore: change test targets

- README.md
Also some IDEs already reporting the wrong type
Plus quite problematic in lib/monitor/watch.js
> docs: delay option as number instead of string, in readme

- lib/monitor/run.js
Two fixes:
1. Allow nodemon to be installed globally and use the dep windows-kill
2. Don't use windows kill on Windows@ < 10
> fix: allow windows users to install globally again

- faq.md
Hello,
I`ve remove the redundant word in the documentation
Fix typo:
the the -> the
> docs: Fix typo in faq.md

- README.md
- package.json
- website/index.html
Node.js is always capitalised in the official docs and most occurrences in nodemon capitalise it, but there were some occurrences where this was not the case. This PR unifies the capitalisation of Node.js.
> Unified Node.js capitalization

- lib/monitor/run.js
Fixes: #1951
This change was suggested in https://github.com/remy/nodemon/issues/1951#issuecomment-1003362605 and I've verified it fixes the issue.
> fix: support windows by using path.delimiter

- bin/nodemon.js
- package-lock.json
- package.json
- Closes #1961
- Closes #2028
- Fixes security issue with `got` (CVE-2022-33987)
- Replace `update-notifier` with `simple-update-notifier` which does the same thing but has one dependency (`semver`) rather than several
- Same caching settings as `update-notifier`
> fix: Replace update notifier with simplified deps

- package-lock.json
- package.json
I know it's just a formality, but our customers are obsessed with audit logs and they are going crazy about vulnerability in `minimatch@3.0.4`.
> chore: upgrade minimatch dependency to 3.1.2

- .npmignore
Adds the following files to `.npmignore` since they aren't needed in the installed package:
- `.eslintrc.json`
- `.jshintrc`
- `.releaserc`
- `.travis.yml`
- `commitlint.config.js`
> chore: add unused files to .npmignore

- lib/monitor/run.js
- lib/spawn.js
If nodemon is started without it's own console (example: via pm2) on Windows, it spawns console windows for it's monitored processes. This should get rid of this behaviour.
> Get rid of spawning shell windows if nodemon is started without console.

- lib/config/defaults.js
> fix: remove ts mapping if loader present

- lib/monitor/run.js
currently it is not possible to to set the `PATH` env because nodemon is overwriting it, this pr will first check if the user passed the `PATH` env and use that, otherwise default to `process.env.PATH`
> allow user set PATH

- package-lock.json
- package.json
> Address vuln in semver (bump simple-update-notifier & semver)

- lib/monitor/watch.js
- lib/utils/index.js
IBM i does not support fs.watch
https://nodejs.org/api/fs.html#caveats
Therefore we always want to use polling on IBM i systems
> feat: always use polling on IBM i

- .github/workflows/release.yml
The latest release job failed https://github.com/remy/nodemon/actions/runs/5484732578 because it couldn't find any runner.
Since the other jobs run on ubuntu-latest, I imagine this would unblock the release
> Update release.yml to use ubuntu-latest

- README.md
When figuring this out it enabled me to ignore everything in node_modules but my own `@yikesable/` scoped modules:
```json
"ignoreRoot": [
"**/node_modules/!(@yikesable)*",
"**/node_modules/**/node_modules"
],
```
Especially handy when working with npm link and modifying ones scoped modules as part of ones main application.
> docs: link to advanced globbing syntax

- lib/monitor/watch.js
This change enables nodemon to watch for file removal events. I tested it on a simple app which enables creation and deletion of JSON files while reflecting changes in the GUI. The change does not appear to cause any issues, although I did not perform extensive tests.
> feat: Enable nodemon to monitor file removal

- .github/workflows/node.js.yml
- .github/workflows/release.yml
- index.d.ts
- jsconfig.json
- lib/nodemon.js
- package.json
Hopefully helps devs use nodemon as required and adds some advice in tools like VS Code.
> fix: add types to help with required nodemon usage

- TEMP_TEST_TS.ts
- index.d.ts
As per discussion in: https://github.com/remy/nodemon/issues/2206
feat(types): export types
feat(types): add default export
@remy I added two TODO's with questions. Also the TEMP_TEST_TS file is just there for you to easier test it locally, I will remove it before merging.
BR,
Kev
> fix: Type exports correctly

- index.d.ts
Fix types for export in file index.d.ts
- use typescript
- set `"type": "module"` in package.json or set extention file to .mts
```
import nodemon from 'nodemon';
// no show error on ide and also when compile the code
// but error when running
nodemon.default();
// show error on ide and also when compile the code
// but no error when running
nodemon();
```
> Fix types for export on ESModule
