remy/nodemon

lib/config/checkWatchSupport.js, lib/monitor/index.js, lib/monitor/offset.js, lib/monitor/watch.js, lib/nodemon.js, lib/utils/index.js, package.json, test/fork/watch-restart.test.js, test/monitor/run.test.js
Closes #455
Closes #453
Fixes #419
This method creates a file and checks the stat to check of an offset between the date on the machine and the created time on the file system. Docker (in my tests) show that you can get the offset using this method.
Once we have the offset, we tell the user (once) and then we use that to find files that have been modified according to the offset (either looking in the last using -mmin or in the future using -newer + a touched file).
=> Find on linux and detect container offset

README.md
I believe the following modification clarifies the original intent of the sentence.
=> Clarify intro sentence in README.md

README.md, faq.md
Explain the issue around ubuntu and nothing running.
[skip ci]
=> Fixed #457

faq.md
=> Close #456

lib/config/exec.js, lib/monitor/run.js
Support spaces in exec - the user must escape using the `^` character as per http://superuser.com/a/279121
=> Fixed #474

lib/monitor/run.js
Fixes #497
Huge props to @xzyfer for solving it over [twitter](https://twitter.com/xzyfer/status/565525891678482432)
=> Fix the pattern match for windows escaping

faq.md
=> Updated FAQ `forever` entry.

faq.md
Something was wrong with the first code example in the forever entry.
Sorry about that, should've checked the formatting before creating #525.
=> Fixed formatting of FAQ entry.

lib/config/index.js, lib/monitor/watch.js
See this issue:
https://github.com/remy/nodemon/issues/555
=> Fixes watch interval

doc/cli/help.txt, lib/cli/parse.js, lib/config/defaults.js, lib/nodemon.js, lib/utils/index.js, lib/utils/log.js, test/utils/log.test.js
via cli --no-color/--no-colour and via nodemon.json colours: false
Supercedes #431
=> feat: support disabling colour output

lib/monitor/watch.js, test/monitor/run.test.js
Fixes #664
Also includes tests and quietens the force crash test (though unchanged).
=> fix: restart on new files added to watched dir

README.md
I tried to use globbing with `--watch` and spent some frustrating time working out that I was being an idiot. Just popped a line in docs to help others.
=> [docs] note on unix globs and --watch

lib/monitor/watch.js
It doesn't look like ideal solution but it fixes #698
=> Save readiness state on a per-watcher basis

README.md
=> docs: fix a typo in readme

.travis.yml, lib/config/exec.js
Want to try and land the appropriate regex substitution from #787 here, but running into some issues with adding a test for it. cc @remy 
[![selfie-0](http://i.imgur.com/w4KzYS1.gif)](https://github.com/thieman/github-selfies/)
=> Support for unicode extensions

.travis.yml, lib/config/exec.js, test/cli/exec.test.js
Successor to #788.
Annoying that my push doesn't add to @lewiscowper's original PR...
=> Lewiscowper: support for unicode extensions

README.md
Closes #324
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/remy/nodemon/914)
=> Update README: delay option in nodemon.js

lib/config/index.js, lib/monitor/run.js
Fixes #521 
Todo:
About unit tests, any recommendation on how I should approach it, where I should put the test?
=> Configurable signals

docs/index.html
Hi,
Really useful module you have here!
I made a tiny change to the CSS of the Docs, just to give the content a bit more space.
Hope you'll like it! 😊
=> A tiny tweak to the Docs CSS 💅

README.md
=> io.js is no longer a thing

README.md
=> Use npx to run dev dependencies

lib/nodemon.js
Quick fix to a minor irritant.
=> fix: help truncation on node 6.2 (#842)

lib/cli/parse.js, test/cli/parse.test.js
=> Add signal CLI flag

lib/config/load.js
=> feat: exit when fail to parse the config file

lib/monitor/run.js
This seems to fix issue #1095 but I could not run tests because of the issue with checking out the repository on Windows: #885
=> Fix: crash when passing argument to node #1095

README.md
@remy We have found that by having the sponsor embed code at the bottom, it ends up being more effective to help fund the project.
=> Reposition Code Sponsor

faq.md
The changes i proposed isworks fine with linux and mac
=> Updated FAQ with added platform documentation

lib/config/defaults.js, lib/monitor/watch.js
Fixes a range of issues, including:
Fixes #1115
=>  feat: disable chokidar globbing on windows

.gitignore, .travis.yml, package.json
enforce node 4 instead of node 6 as minimum.
all tests pass under node 4
=> node 4 min

.travis.yml, lib/monitor/run.js, lib/monitor/watch.js, test/monitor/run.test.js
=> test: fork child node processes

lib/config/exec.js, lib/config/load.js, package.json, test/cli/exec.test.js, test/cli/parse.test.js
With support for custom extensions (picking only the first).
Fixes #1165
=> fix: support nodemon index to expand to index.js

lib/monitor/watch.js
Addresses https://github.com/remy/nodemon/issues/1169
=> fixed an issue where null was being passed to path.resolve()

lib/monitor/run.js, package-lock.json, package.json
=> fix: nodemon reporting crash

test/config/env.test.js, test/config/load.test.js, test/fork/watch-restart.test.js, test/monitor/ignore.test.js, test/monitor/match.test.js, test/monitor/run.test.js, test/monitor/watch-restart.test.js
I can't explain this. Sorry :)
The test were hanging randomly and intermittently for me - so I started debugging and adding `console.log`s here and there - and all of a sudden they started passing. So I figured it's something to do with delaying the execution? Possibly something related to promises and event loops and watches created in the same tick. Unsure. But adding a timeout seems to make things a _lot_ more stable? 
I assume the last test was hanging for the same reason?
I could also be wrong... but worth trying?
=> test: fix hanging test

lib/cli/parse.js, test/cli/parse.test.js
Fixes #750
See new tests for details
=> fix: ensure non-slurp is passed to script

package.json
=> fix: fail gracefully if postinstall fails

lib/monitor/match.js, lib/monitor/run.js, lib/spawn.js, lib/utils/index.js, package-lock.json, package.json, test/events/complete.test.js, test/fork/change-detect.test.js, test/monitor/match.test.js
=> fix: node < 6.4.0 can't connect to stdin

lib/monitor/watch.js, test/monitor/match.test.js
=> fix: ensure directories are watched, not files

lib/config/load.js, lib/monitor/run.js, lib/nodemon.js
=> fix: only hook SIGINT on boot - not at require

lib/config/exec.js, test/cli/parse.test.js
=> fix: {{filename}} is only replaced once

lib/monitor/match.js, lib/monitor/watch.js
=> fix: in watch, use fully filtered ignore rules

faq.md
=> FAQ update to address Docker restarts

README.md, doc/events.md
I was trying to find out how to use nodemon as child process, and stumble upon this https://github.com/remy/nodemon/issues/1018
So adding more docs for other people later to make it clearer how to do it.
=> docs: more docs for nodemon as child process

doc/cli/help.txt, lib/monitor/match.js, test/monitor/match.test.js
=>  fix: allow watching relative path files

lib/nodemon.js
And refactor the stdin handling.
/ht @KlaussMC for making me realise that `ctrl-l` is ignored.
=> feat: support ctrl+l

README.md
change README.md intro to clarify and remove redundant text
=> docs: change README.md to make the intro more concise

faq.md
=> docs: faq typo fix

README.md
Center the Nodemon logo in the `README.md` for a slightly better look.
=> docs: center logo

lib/monitor/run.js
=> fix: disable fork only if string starts with dash

lib/monitor/run.js
add event to listen to messages coming from the child's ipc events, partially implementing #1519
see https://github.com/remy/nodemon/issues/1519#issuecomment-481030466
=> feat: add message event

README.md
- `less` is used for singular mass nouns
- `fewer` when discussing countable things
=> docs: README Grammar

lib/nodemon.js
ref: #1583
It was unclear whether it was listing files being watched when in fact
it was the list of directories (plus, make it cleaner)
=> fix: language around "watching"

lib/nodemon.js
PR based on https://github.com/remy/nodemon/issues/1528#issuecomment-470149782
=> fix: to avoid confusion like in #1528, always report used extension

README.md, doc/cli/help.txt, doc/cli/options.txt, lib/config/exec.js, package-lock.json, test/cli/exec.test.js, test/cli/parse.test.js, test/config/load.test.js, test/fixtures/global/nodemon.json, test/fixtures/packages/express4/package.json, test/fixtures/watch-count/node_modules/express/node_modules/accepts/node_modules/mime-types/node_modules/mime-db/db.json, test/monitor/match.test.js
=> Replace `jade` references by `pug`

README.md
20k stars and nobody noticed? 🤔
=> docs: Fix run-on sentence

bin/postinstall.js
Refs #1765#issuecomment-732983013
=> fix: postinstall hide message in CI

lib/nodemon.js
Fixes: #1807
Allows for nodemon --help > help.txt
=> fix: redirect help

README.md
Sorry if the duplication was intentional.
HTH
=> docs: Remove duplicate info about using the `main`

lib/monitor/run.js
=> fix: allow windows users to install globally again

doc/sample-nodemon.md
=> docs: add syntax highlighting to sample-nodemon.md (#1982)

package.json
Fix for this issue: https://github.com/remy/nodemon/issues/2023
=> Update update-notifier to v6.0.0

README.md
I was looking for unix globbing support and found out it is supported if we quote the globbing pattern (https://github.com/remy/nodemon/issues/1240).
Here is a proposal to update the documentation, as suggested in the issue.
=> Update documentation about support for unix globbing

README.md
updated README.md , added hyperlink to banner, it might be beneficial , please check
closes #1943
=> docs: added link on banner

faq.md
As requested, adding some information on how to solve a race condition related to the `--inspect` flag to the FAQ.
Source issue: https://github.com/remy/nodemon/issues/2056
=> docs: add workaround for inspect problem to faq.md

index.d.ts
=> fix: cast the nodemon function as Nodemon type

index.d.ts
Fixes https://github.com/remy/nodemon/issues/2223
=> fix: add missing ignore option to type defintion of config
